// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO5cjU1Ax-tX2bUsok7A0gN91eQn174EQ',
    appId: '1:417755611342:web:2abeb2150791e51e2a109f',
    messagingSenderId: '417755611342',
    projectId: 'doctor-app-c7769',
    authDomain: 'doctor-app-c7769.firebaseapp.com',
    storageBucket: 'doctor-app-c7769.firebasestorage.app',
    measurementId: 'G-YF7SWD88HB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYQCCACq-GIkeaUYm34zoZv_UxaUCUa9Q',
    appId: '1:417755611342:android:a4547cca9fd317db2a109f',
    messagingSenderId: '417755611342',
    projectId: 'doctor-app-c7769',
    storageBucket: 'doctor-app-c7769.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6lfGL5ZuSi7mzCWeZ5-wfoo3v_M69bxk',
    appId: '1:417755611342:ios:565c1830c9b91f2c2a109f',
    messagingSenderId: '417755611342',
    projectId: 'doctor-app-c7769',
    storageBucket: 'doctor-app-c7769.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6lfGL5ZuSi7mzCWeZ5-wfoo3v_M69bxk',
    appId: '1:417755611342:ios:565c1830c9b91f2c2a109f',
    messagingSenderId: '417755611342',
    projectId: 'doctor-app-c7769',
    storageBucket: 'doctor-app-c7769.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO5cjU1Ax-tX2bUsok7A0gN91eQn174EQ',
    appId: '1:417755611342:web:cc16119474524a882a109f',
    messagingSenderId: '417755611342',
    projectId: 'doctor-app-c7769',
    authDomain: 'doctor-app-c7769.firebaseapp.com',
    storageBucket: 'doctor-app-c7769.firebasestorage.app',
    measurementId: 'G-ZV7QDF3ZZJ',
  );

}